name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.x

    - name: Checkout src
      uses: actions/checkout@v2

    - name: Go get
      run: |
        go get -v -t -d ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.55

    - name: Go build
      run: go build -v .

    - name: Go test
      run: go test -v .
